// Encrypted backup data — generated by "백업 생성" / "Create Backup"
// Paste the base64 string from the app into ENCRYPTED_BACKUP below, or leave empty.
// Do not commit real backup strings to a public repository; keep them local only.
const ENCRYPTED_BACKUP = '';
